"""Initial migration

Revision ID: 2a4309568eba
Revises: 
Create Date: 2023-09-26 12:07:26.760971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a4309568eba'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chunk_hash_id', sa.String(), nullable=True),
    sa.Column('faiss_index', sa.Integer(), nullable=True),
    sa.Column('document_key', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('collection', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chunk_hash_id')
    )
    op.create_table('integration_registry_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('auth_method', sa.String(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plugin_registry_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('icon', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('settings_metadata', sa.JSON(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('preset_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('plugins', sa.JSON(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('is_custom', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('space_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('profile', sa.JSON(), nullable=True),
    sa.Column('app_state', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversation_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('space_id', sa.Integer(), nullable=True),
    sa.Column('preset_id', sa.Integer(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['preset_id'], ['preset_model.id'], ),
    sa.ForeignKeyConstraint(['space_id'], ['space_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('function_registry_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('plugin_id', sa.Integer(), nullable=True),
    sa.Column('settings_metadata', sa.JSON(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['plugin_id'], ['plugin_registry_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('integration_instance_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('integration_id', sa.Integer(), nullable=True),
    sa.Column('credentials', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['integration_id'], ['integration_registry_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approval_request_model',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('tool_name', sa.String(), nullable=True),
    sa.Column('tool_args', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversation_document',
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation_model.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['document_model.id'], )
    )
    op.create_table('function_integration',
    sa.Column('function_id', sa.Integer(), nullable=True),
    sa.Column('integration_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['function_id'], ['function_registry_model.id'], ),
    sa.ForeignKeyConstraint(['integration_id'], ['integration_registry_model.id'], )
    )
    op.create_table('message_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('actions', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plugin_instance_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('plugin_id', sa.Integer(), nullable=True),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('settings_values', sa.JSON(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation_model.id'], ),
    sa.ForeignKeyConstraint(['plugin_id'], ['plugin_registry_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('function_instance_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('function_id', sa.Integer(), nullable=True),
    sa.Column('plugin_instance_id', sa.Integer(), nullable=True),
    sa.Column('settings_values', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['function_id'], ['function_registry_model.id'], ),
    sa.ForeignKeyConstraint(['plugin_instance_id'], ['plugin_instance_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('function_instance_model')
    op.drop_table('plugin_instance_model')
    op.drop_table('message_model')
    op.drop_table('function_integration')
    op.drop_table('conversation_document')
    op.drop_table('approval_request_model')
    op.drop_table('integration_instance_model')
    op.drop_table('function_registry_model')
    op.drop_table('conversation_model')
    op.drop_table('user_model')
    op.drop_table('space_model')
    op.drop_table('preset_model')
    op.drop_table('plugin_registry_model')
    op.drop_table('integration_registry_model')
    op.drop_table('document_model')
    # ### end Alembic commands ###
